version: "3.9"
services:
  db:
    image: mysql
    # NOTE: use of "mysql_native_password" is not recommended: https://dev.mysql.com/doc/refman/8.0/en/upgrading-from-previous-series.html#upgrade-caching-sha2-password
    # (this is just an example, not intended to be a production configuration)
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: qwerty32
      MYSQL_DATABASE: medika
      PORT: 80
      SQL_HOST: db
      SQL_USER: root
      SQL_PASSWORD: qwerty
      SQL_PORT: 3306
      SQL_DBNAME: medika
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d
  phpmyadmin:
    image: phpmyadmin
    restart: always
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
    ports:
      - 8080:80
    depends_on:
      - db