# # Utiliser la version de Node.js qui correspond à votre environnement de développement
# FROM node:20

# # Définir le répertoire de travail dans le conteneur
# WORKDIR /usr/src/app

# # Copier les fichiers package.json et package-lock.json
# COPY package*.json ./

# # Installer les dépendances du projet
# RUN npm install

# # Copier tous les fichiers du projet backend dans le répertoire de travail du conteneur
# COPY . .

# # Exposer le port sur lequel votre application va s'exécuter
# EXPOSE 3000

# # Définir la commande pour démarrer votre application
# CMD [ "npm", "run", "dev" ]
